import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@mui/material/styles';
import { colors } from '../styles/colors'
import { theme } from '..//theme'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
      <body className={roboto.className} style={{ backgroundColor: '#F6F7F9'}}>
        {children}
      </body>
    </ThemeProvider>

    </html>
  )
}
